/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtistNameRouteImport } from './routes/artist.$name'
import { Route as ApiTrendingArtistsRouteImport } from './routes/api/trending-artists'
import { Route as ApiMusicTrendingRouteImport } from './routes/api/music-trending'
import { Route as ApiMusicTrackRouteImport } from './routes/api/music-track'
import { Route as ApiMusicSearchRouteImport } from './routes/api/music-search'
import { Route as ApiLyricsRouteImport } from './routes/api/lyrics'
import { Route as ApiArtistImageRouteImport } from './routes/api/artist-image'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistNameRoute = ArtistNameRouteImport.update({
  id: '/artist/$name',
  path: '/artist/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrendingArtistsRoute = ApiTrendingArtistsRouteImport.update({
  id: '/api/trending-artists',
  path: '/api/trending-artists',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMusicTrendingRoute = ApiMusicTrendingRouteImport.update({
  id: '/api/music-trending',
  path: '/api/music-trending',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMusicTrackRoute = ApiMusicTrackRouteImport.update({
  id: '/api/music-track',
  path: '/api/music-track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMusicSearchRoute = ApiMusicSearchRouteImport.update({
  id: '/api/music-search',
  path: '/api/music-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLyricsRoute = ApiLyricsRouteImport.update({
  id: '/api/lyrics',
  path: '/api/lyrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArtistImageRoute = ApiArtistImageRouteImport.update({
  id: '/api/artist-image',
  path: '/api/artist-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/api/artist-image': typeof ApiArtistImageRoute
  '/api/lyrics': typeof ApiLyricsRoute
  '/api/music-search': typeof ApiMusicSearchRoute
  '/api/music-track': typeof ApiMusicTrackRoute
  '/api/music-trending': typeof ApiMusicTrendingRoute
  '/api/trending-artists': typeof ApiTrendingArtistsRoute
  '/artist/$name': typeof ArtistNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/api/artist-image': typeof ApiArtistImageRoute
  '/api/lyrics': typeof ApiLyricsRoute
  '/api/music-search': typeof ApiMusicSearchRoute
  '/api/music-track': typeof ApiMusicTrackRoute
  '/api/music-trending': typeof ApiMusicTrendingRoute
  '/api/trending-artists': typeof ApiTrendingArtistsRoute
  '/artist/$name': typeof ArtistNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/api/artist-image': typeof ApiArtistImageRoute
  '/api/lyrics': typeof ApiLyricsRoute
  '/api/music-search': typeof ApiMusicSearchRoute
  '/api/music-track': typeof ApiMusicTrackRoute
  '/api/music-trending': typeof ApiMusicTrendingRoute
  '/api/trending-artists': typeof ApiTrendingArtistsRoute
  '/artist/$name': typeof ArtistNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/library'
    | '/onboarding'
    | '/search'
    | '/settings'
    | '/api/artist-image'
    | '/api/lyrics'
    | '/api/music-search'
    | '/api/music-track'
    | '/api/music-trending'
    | '/api/trending-artists'
    | '/artist/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/library'
    | '/onboarding'
    | '/search'
    | '/settings'
    | '/api/artist-image'
    | '/api/lyrics'
    | '/api/music-search'
    | '/api/music-track'
    | '/api/music-trending'
    | '/api/trending-artists'
    | '/artist/$name'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/library'
    | '/onboarding'
    | '/search'
    | '/settings'
    | '/api/artist-image'
    | '/api/lyrics'
    | '/api/music-search'
    | '/api/music-track'
    | '/api/music-trending'
    | '/api/trending-artists'
    | '/artist/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  LibraryRoute: typeof LibraryRoute
  OnboardingRoute: typeof OnboardingRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  ApiArtistImageRoute: typeof ApiArtistImageRoute
  ApiLyricsRoute: typeof ApiLyricsRoute
  ApiMusicSearchRoute: typeof ApiMusicSearchRoute
  ApiMusicTrackRoute: typeof ApiMusicTrackRoute
  ApiMusicTrendingRoute: typeof ApiMusicTrendingRoute
  ApiTrendingArtistsRoute: typeof ApiTrendingArtistsRoute
  ArtistNameRoute: typeof ArtistNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$name': {
      id: '/artist/$name'
      path: '/artist/$name'
      fullPath: '/artist/$name'
      preLoaderRoute: typeof ArtistNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trending-artists': {
      id: '/api/trending-artists'
      path: '/api/trending-artists'
      fullPath: '/api/trending-artists'
      preLoaderRoute: typeof ApiTrendingArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/music-trending': {
      id: '/api/music-trending'
      path: '/api/music-trending'
      fullPath: '/api/music-trending'
      preLoaderRoute: typeof ApiMusicTrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/music-track': {
      id: '/api/music-track'
      path: '/api/music-track'
      fullPath: '/api/music-track'
      preLoaderRoute: typeof ApiMusicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/music-search': {
      id: '/api/music-search'
      path: '/api/music-search'
      fullPath: '/api/music-search'
      preLoaderRoute: typeof ApiMusicSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lyrics': {
      id: '/api/lyrics'
      path: '/api/lyrics'
      fullPath: '/api/lyrics'
      preLoaderRoute: typeof ApiLyricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/artist-image': {
      id: '/api/artist-image'
      path: '/api/artist-image'
      fullPath: '/api/artist-image'
      preLoaderRoute: typeof ApiArtistImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  LibraryRoute: LibraryRoute,
  OnboardingRoute: OnboardingRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  ApiArtistImageRoute: ApiArtistImageRoute,
  ApiLyricsRoute: ApiLyricsRoute,
  ApiMusicSearchRoute: ApiMusicSearchRoute,
  ApiMusicTrackRoute: ApiMusicTrackRoute,
  ApiMusicTrendingRoute: ApiMusicTrendingRoute,
  ApiTrendingArtistsRoute: ApiTrendingArtistsRoute,
  ArtistNameRoute: ArtistNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
